### ISSUE TITLE
Issue/Request could you add velocity support?

### ISSUE THREAD

**Issue by pietru2004** [Gamerexde/HideMyPlugins#1]
I get error when running HideMyPlugins at velocity proxy - faster and easier proxy.
[log.txt](https://github.com/Gamerexde/HideMyPlugins/files/4924560/log.txt)

Is there chance for velocity support ?

**Comment by Gamerexde** [comment]
Hi.

Right now HideMyPlugins only supports Spigot and BungeeCord (and his forks), Velocity is based on a entire diferent API, and Velocity cannot understand BungeeCord's code, that's why it dosen't work.

I will try to support Velocity but that may come out in a while, and I can't assure you that will be implemented since working with diferent API at the same time is a bit tedious, and may require re-writes on the code.

**Comment by pietru2004** [comment]
thank, ao I need to add my plugin to all my paper serves, eh...
